# Generated by Django 2.2.3 on 2019-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
