# Generated by Django 2.2.3 on 2019-08-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190801_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d'),
        ),
    ]
